import { Fonts } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  content: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  authScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 40,
    alignItems: 'center',
  },
  topSection: {
    alignItems: 'center',
    marginBottom: 40,
    width: '100%',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  logoCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  logoText: {
    fontSize: 24,
    fontFamily: Fonts.title,
    fontWeight: 'bold',
  },
  imageContainer: {
    width: 260,
    height: 260,
    alignItems: 'center',
    justifyContent: 'center',
  },
  glowCircle: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#FFE0B2',
    opacity: 0.3,
  },
  mainCircle: {
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBox: {
    width: 80,
    height: 80,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  smallIcon: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'white',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  pos1: {
    top: 10,
    right: 15,
  },
  pos2: {
    bottom: 20,
    left: 10,
  },
  pos3: {
    bottom: 60,
    right: -5,
  },
  textSection: {
    alignItems: 'center',
    marginBottom: 40,
  },
  title: {
    fontSize: 32,
    fontFamily: Fonts.title,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 16,
    fontFamily: Fonts.body,
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 20,
  },
  formSection: {
    width: '100%',
    marginBottom: 40,
  },
  input: {
    width: '100%',
    height: 56,
    borderRadius: 28,
    paddingHorizontal: 24,
    fontSize: 16,
    fontFamily: Fonts.body,
  },
  errorText: {
    marginTop: 10,
    fontSize: 12,
    fontFamily: Fonts.body,
    color: '#D32F2F',
    textAlign: 'center',
  },
  smartErrorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEBEE',
    padding: 12,
    borderRadius: 16,
    marginTop: 16,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(211, 47, 47, 0.1)',
  },
  errorIconBox: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(211, 47, 47, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  smartErrorText: {
    fontSize: 13,
    fontFamily: Fonts.body,
    color: '#D32F2F',
    flex: 1,
    lineHeight: 18,
    fontWeight: '600',
  },
  infoSection: {
    width: '100%',
    marginBottom: 40,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 1,
  },
  infoIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  infoText: {
    fontSize: 14,
    fontFamily: Fonts.body,
    fontWeight: '600',
    flex: 1,
  },
  buttonSection: {
    width: '100%',
    alignItems: 'center',
  },
  primaryButton: {
    width: '100%',
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 4,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: Fonts.title,
  },
  secondaryButton: {
    width: '100%',
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: 'white',
    marginBottom: 20,
  },
  secondaryButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: Fonts.title,
  },
  textButton: {
    padding: 10,
  },
  textButtonText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: Fonts.title,
  },
  otpSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 24,
  },
  otpInput: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 1,
  },
  otpText: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  resendSection: {
    marginBottom: 40,
    alignItems: 'center',
  },
  resendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  resendText: {
    fontSize: 12,
    fontFamily: Fonts.body,
    fontWeight: 'bold',
    marginLeft: 6,
  },
  backButtonTop: {
    position: 'absolute',
    left: 0,
    top: -20,
    padding: 10,
    zIndex: 10,
  },
  securityOptionsSection: {
    width: '100%',
    marginBottom: 32,
  },
  securityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    borderRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  securityIconBox: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  securityTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: Fonts.title,
  },
  securitySubtitle: {
    fontSize: 12,
    fontFamily: Fonts.body,
    marginTop: 2,
  },
  footerText: {
    fontSize: 12,
    fontFamily: Fonts.body,
    textAlign: 'center',
    verticalAlign: 'middle',
  },
  pinDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  pinDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.5,
    marginHorizontal: 6,
  },
  forgotPinButton: {
    marginBottom: 20,
  },
  forgotPinText: {
    fontSize: 12,
    fontFamily: Fonts.body,
    textAlign: 'center',
  },
  faceIdButton: {
    alignItems: 'center',
    marginBottom: 20,
  },
  faceIdIconBox: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 3,
  },
  faceIdText: {
    fontSize: 12,
    fontFamily: Fonts.body,
    fontWeight: '600',
  },
  keypadGrid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  keypadButton: {
    width: '30%',
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 14,
  },
  keypadDigit: {
    fontSize: 22,
    fontFamily: Fonts.title,
    fontWeight: '700',
  },
  keypadHelper: {
    fontSize: 10,
    fontFamily: Fonts.body,
    textAlign: 'center',
    lineHeight: 14,
  },
});
